exports.LOGIN_TYPE = {
  GOOGLE: 1,
  QUICK: 2,
  MOBILE_NUMBER: 3,
  EMAIL_PASSWORD: 4,
};

exports.LISTENER_REQUEST_STATUS = {
  PENDING: 1,
  ACCEPTED: 2,
  DECLINED: 3,
};

exports.HISTORY_TYPE = {
  LOGIN_BONUS: 1,
  COIN_PLAN_PURCHASE: 2,
  PRIVATE_AUDIO_CALL: 3,
  PRIVATE_VIDEO_CALL: 4,
  RANDOM_AUDIO_CALL: 5,
  RANDOM_VIDEO_CALL: 6,
  WITHDRAWAL_BY_LISTENER: 7,
  AVATAR_UNLOCK: 8,
  DAILY_REWARD: 9,
  GIFT: 10,
  PROFILE_REWARD: 11,
  REFERRAL_REWARD: 12,
  AVATAR_BONUS: 13,
  PREMIUM_PASS: 14,
  STYLE_UNLOCK: 15,
};

exports.MESSAGE_TYPE = {
  MESSAGE: 1,
  IMAGE: 2,
  AUDIO: 3,
  AUDIO_CALL: 4,
  VIDEO_CALL: 5,
  GIFT: 6,
};

exports.CALL_TYPE = {
  RECEIVED: 1,
  DECLINED: 2,
  MISCALLED: 3,
};

exports.WITHDRAWAL_STATUS = {
  DEFAULT: 0,
  PENDING: 1,
  ACCEPTED: 2,
  DECLINED: 3,
};
